name: Unit tests

on:
  push:
    paths:
      - '**.go'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.0.0
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.16'
        id: go
      - name: Go mod verify
        run: go mod verify

      - name: Get credentials
        id: vault
        uses: hashicorp/vault-action@v3.3.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.ROLE_ID }}
          secretId: ${{ secrets.SECRET_ID }}
          tlsSkipVerify: true
          exportEnv: false
          namespace: admin/tpgw
          secrets: |
                gcp/key/tf-acctest private_key_data
      - name: Run unit tests
        run:
          export GOOGLEWORKSPACE_CREDENTIALS=$(echo -n ${{ steps.vault.outputs.private_key_data }} | base64 --decode)
          make test